name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quizbox_img:$(date +%s)
    - name: Run the docker container
      run: docker run --name quizbox_ct:$(date +%s) -p 3000:3000 quizbox_img:$(date +%s)
